language: c

env:
    - TRAVIS_PYTHON_VERSION="2.7"
    - TRAVIS_PYTHON_VERSION="3.4"
    - TRAVIS_PYTHON_VERSION="3.5"
    global:
      secure: LBM9j33dtDtx7p/pXlcCYucnIXSq0KUwuOL2BZ61+wO/OsPojshr7x3x1fnyLWiCSclgF3he96+StQQ3wd8E/I1d+Tpb/LHa57Rr48khC6L4cMPIsLnD4bPS19/6sRN0sn8Nzo586xWEFWhh9HJF/GCbMgiFcIB+sdpAVKYds+PjxiSe01HR6HVxDwkdnrTBTkIYbZyQyFLqhpl1yTBlz4D27PZRZpNKYQMzDVz5XR/gKLvg1zgkAIbi25uOL2q6VU446GqIod9DfmCDiJT99ggEc2KvzTgXhx9r0Vz/QX042cNjQCwAt21OEALRs9mtr3jxcOXIEJDC4CngX2xG2YkAPgIRSIYwxe6WwWTIB/7I9bCPyy6c8CUDzyKlwOSjlQV70NKcmj8ZJvaphnzioIPOtSwgLjXFoRp67TclkwnATS3soru0vZRhciMcpv9F/KSLZTI2WWWl7qW8nHtc/NS2piQw6VaWrNOg+kNlHL1PeMgq1lFOREsrtMlLTJhWCdw9ei6Jnm/WlvXsLlh0z81O1w3n5TtpNhfm1XRiXylgpIr6SYIFOBKXf00UnrjsDsq/jM56KZfOZQYH1w1URM0KK75sdgFVeUIpVtm/s8f66GG5hBJwUYXUO4TZqmIpTtQCu+vYTfApWXY3irxWSIdG3LGMmtSLNAC8z4k96FU=

os:
    - linux
    - osx

dist: trusty

before_install:
    - echo -e "machine github.com\n  login ci-user\n  password $CI_USER_PASSWORD" >> ~/.netrc
    # get access to private fastFM-core2 subrepo
    - openssl aes-256-cbc -K $encrypted_36432524a830_key -iv $encrypted_36432524a830_iv
      -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/deploy_rsa
    - ssh-add /tmp/deploy_rsa
      # fastFM-core depends on cblas
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y libopenblas-dev; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" =~ "^2" ]]; then
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
        fi
      else
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        fi
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cython numpy pandas scipy scikit-learn nose
    - source activate test-environment

install:
    - git submodule update --init --recursive
    - make
    - python setup.py bdist_wheel
    - pip install dist/*.whl

script:
    - nosetests

before_deploy:
    - export RELEASE_PKG_FILE=$(ls dist/*.whl)
    - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: AJcZoe2+OiMJ4VlSkASAeMc/ii0ZRnj2PFaaL7zlSbx1THMpY/49U5BSyqX1PQioPSlTV3ZsIXI3u7KyqoXIQSXWzAuaBzpLTLS85fGSuTvUuexmaJtKU92OC143tuVVLCPnjC992+1uyctjrxMSqgoaUolfYkEftt5RGrMIKl2duGfDXrPXIueHSl8FQGXkmlY6NqkRx2v5kxsAjFcurvwTNU8ptJ84jVKjrE6t1IB61vp2eUcqVR/z6Lwau6mdvIybglnbH4lCMXP98zEIibLA8vbn3XxrC+0uU7Kjz37K6/CsJEPNL5tujJDMRKAupnrkgPsAGTpsAn6O6uLUz0ISgcen8R6KJ7cBli+cq08OZ3JLLoJpqkni62YVSQV+uYkQk9b5Pu09vUTOozJMnOqLSj9hVIswyxGiFPcTFskMgqMdx15M59gd0YpXH633YqwBgRmWNsctp4BKnTaE3iGW6aZc8lrXxpL7qcVAosjmpjLp3jiPXVSRdYf0yHl6pDUj5ZVyu27kAn1/I9JL0nH19zjXF2tUlEjuT9ydHwnhmsgBN/V+JhZxi7ZeEbOZfY1MfekKM/NwSRehVEp/J0XWqWg+kIXRU/rqY1/w0vLVNFeQirpEjUp39eCBydXeS3Bik8uANW2UTxojJo3LBfLLoAT8ZWFb3YrIBAYkzjc=
  file: ${RELEASE_PKG_FILE}
  skip_cleanup: true
  on:
    tags: true
