language: c
env:
  global:
  - secure: yg9UefZmuAESNCeE3BzDHhpb/sC7PnAsz0k+i63CN0HHZW7IOheqNJFpJlXpEmPKf/b59MOX6PnNNyCkoPnZaNqIvCTd1Msxd365RtOPdmTQQOegkMbKurxsbDUxDe2VnFQ/xjYJqQSNFLAhZ5kRyYLpp4zeOJbv/LdApMX0h0wF38GHMnsWPAF05gvYGQOHuocs03KrMz8PIQ4shocIGJXDwivrpxWATieDgY/tuJQxah7+B+p37GvASHaZ4JjHwf5EkJTdaUdjDtTiV8k2Y6EEryzldPy89sqGwg1Wtyu9x/+w4dmRYA+KK/XncDCYS/3xnyCeX6qwD6JpyjMkV27HyZGBNGrbjUu0COh4ZZBgCsdYnRTjHpFvvQQGLdkROWFrbfKu0KCAKviREPAH4jlQbLfsWkbdsIvUAF1Wt9qjot6datcFeS8A8XGIuR66K28JrAq+2QO4DKKqv6G/NwrDlr72/X5/l6Ogy5NqsT6shIgSHySU+S6sy10JwKOhDxH13H2rTs5B1AqFh3OITYbGU/Q+0MB/cAlx5sOepXFzx9x2qzoqPozv/PbSoAB4ifgUpAg/3FevbAs5BKe4o2/jp7dr7sexjMp89djdZbC7AKVYaAEt5gHaA0d0MzhDxF48OINgFIG0FI6L4C4uomXDTgCiG/6NHZhINSoBi2w=
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.4"
  - TRAVIS_PYTHON_VERSION="3.5"
os:
    - linux
    - osx

dist: trusty

before_install:
    # get access to private fastFM-core2 subrepo
    - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
      # fastFM-core depends on cblas
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y libopenblas-dev; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" =~ "^2" ]]; then
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh;
        fi
      else
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        fi
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cython numpy pandas scipy scikit-learn nose
    - source activate test-environment

install:
    #    - git submodule update --init --recursive
    - make
    - python setup.py bdist_wheel
    - pip install dist/*.whl

script:
    - nosetests

before_deploy:
    - export RELEASE_PKG_FILE=$(ls dist/*.whl)
    - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: AJcZoe2+OiMJ4VlSkASAeMc/ii0ZRnj2PFaaL7zlSbx1THMpY/49U5BSyqX1PQioPSlTV3ZsIXI3u7KyqoXIQSXWzAuaBzpLTLS85fGSuTvUuexmaJtKU92OC143tuVVLCPnjC992+1uyctjrxMSqgoaUolfYkEftt5RGrMIKl2duGfDXrPXIueHSl8FQGXkmlY6NqkRx2v5kxsAjFcurvwTNU8ptJ84jVKjrE6t1IB61vp2eUcqVR/z6Lwau6mdvIybglnbH4lCMXP98zEIibLA8vbn3XxrC+0uU7Kjz37K6/CsJEPNL5tujJDMRKAupnrkgPsAGTpsAn6O6uLUz0ISgcen8R6KJ7cBli+cq08OZ3JLLoJpqkni62YVSQV+uYkQk9b5Pu09vUTOozJMnOqLSj9hVIswyxGiFPcTFskMgqMdx15M59gd0YpXH633YqwBgRmWNsctp4BKnTaE3iGW6aZc8lrXxpL7qcVAosjmpjLp3jiPXVSRdYf0yHl6pDUj5ZVyu27kAn1/I9JL0nH19zjXF2tUlEjuT9ydHwnhmsgBN/V+JhZxi7ZeEbOZfY1MfekKM/NwSRehVEp/J0XWqWg+kIXRU/rqY1/w0vLVNFeQirpEjUp39eCBydXeS3Bik8uANW2UTxojJo3LBfLLoAT8ZWFb3YrIBAYkzjc=
  file: ${RELEASE_PKG_FILE}
  skip_cleanup: true
  on:
    tags: true
